
const useIFrame = false;
const populateInfoDelay = 150;
const updateProgressDelay = 400;
const IFrameVerificationDelay = 4000;

const collegeInfo = {
  cornell: {
    name: "Cornell University",
    id: "cornell",
    appType: "Early Decision",
    dateSubmitted: "11/1/2023",
    dateResponse: "12/14/2023",
    collegePortalWebsite: "https://engage.admissions.cornell.edu/account/login",
  },
  purdue: {
    name: "Purdue University",
    id: "purdue",
    appType: "Early Action",
    dateSubmitted: "11/1/2023", 
    dateResponse: "1/12/2024",
    collegePortalWebsite: "https://www.admissions.purdue.edu/apply/applicationstatus.php",
  },
  northeastern: {
    name: "Northeastern University",
    id: "northeastern",
    appType: "Early Action",
    dateSubmitted: "11/1/2023",
    dateResponse: "1/28/2024",
    collegePortalWebsite: "https://apply.northeastern.edu/portal/app_status?utm_campaign=FRapplicant&utm_content=ASC_appacknowledge&utm_medium=email&utm_source=deliver&utm_term=fa24",
  },
  udub: {
    name: "University of Washington",
    id: "udub",
    appType: "Regular Decision",
    dateSubmitted: "11/15/2023",
    dateResponse: "3/1/2024",
    collegePortalWebsite: "https://admit.washington.edu/uw-netid/",
  },
  ut: {
    name: "UT Austin",
    id: "ut",
    appType: "Regular Decision",
    dateSubmitted: "12/1/2023",
    dateResponse: "3/1/2024",
    collegePortalWebsite: "https://bealonghorn.admissions.utexas.edu/portal/mystatus?tab=admissions",
  },
  ucb: {
    name: "UC Berkeley",
    id: "ucb",
    appType: "Regular Decision",
    dateSubmitted: "11/29/2023",
    dateResponse: "3/28/2024",
    collegePortalWebsite: "https://apply.berkeley.edu/apply/status",
  },
  ucsd: {
    name: "UC San Diego",
    id: "ucsd",
    appType: "Regular Decision",
    dateSubmitted: "11/29/2023",
    dateResponse: "3/31/2024",
    collegePortalWebsite: "https://beatriton.ucsd.edu/apply/status",
  },
  ucr: {
    name: "UC Riverside",
    id: "ucr",
    appType: "Regular Decision",
    dateSubmitted: "11/29/2023",
    dateResponse: "3/1/2024",
    collegePortalWebsite: "https://auth.ucr.edu/cas/login?service=https://my.ucr.edu/AccountHome.aspx",
  },
  uci: {
    name: "UC Irvine",
    id: "uci",
    appType: "Regular Decision",
    dateSubmitted: "11/29/2023",
    dateResponse: "3/17/2024",
    collegePortalWebsite: "https://apply.admissions.uci.edu/portal/applicantstatus",
  },
  ucla: {
    name: "UC LA",
    id: "ucla",
    appType: "Regular Decision",
    dateSubmitted: "11/29/2023",
    dateResponse: "3/17/2024",
    collegePortalWebsite: "https://bruins.admission.ucla.edu/myApplication/Status.aspx",
  },
  ucm: {
    name: "UC Merced",
    id: "ucm",
    appType: "Regular Decision",
    dateSubmitted: "11/29/2023",
    dateResponse: "3/1/2024",
    collegePortalWebsite: "https://decision.ucmerced.edu/",
  },
  ucd: {
    name: "UC Davis",
    id: "ucd",
    appType: "Regular Decision",
    dateSubmitted: "11/29/2023",
    dateResponse: "3/10/2024",
    collegePortalWebsite: "https://myadmissions.ucdavis.edu/applicants/current/status/",
  },
  ucsc: {
    name: "UC Santa Cruz",
    id: "ucsc",
    appType: "Regular Decision",
    dateSubmitted: "11/29/2023",
    dateResponse: "3/15/2024",
    collegePortalWebsite: "https://my.ucsc.edu/psc/csprd/EMPLOYEE/SA/c/NUI_FRAMEWORK.PT_AGSTARTPAGE_NUI.GBL?CONTEXTIDPARAMS=TEMPLATE_ID%3aPTPPNAVCOL&scname=ADMN_ADMISSIONS&PTPPB_GROUPLET_ID=SCA_ADMISSIONS&CRefName=ADMN_NAVCOLL_20&PanelCollapsible=Y&AJAXTransfer=Y",
  },
  sjsu: {
    name: "San Jose State University",
    id: "sjsu",
    appType: "Regular Decision",
    dateSubmitted: "11/29/2023",
    dateResponse: "2/1/2024",
    collegePortalWebsite: "https://one.sjsu.edu/",
  },
  gt: {
    name: "Georgia Tech",
    id: "gt",
    appType: "Regular Decision",
    dateSubmitted: "1/2/2024",
    dateResponse: "3/24/2024",
    collegePortalWebsite: "https://application.gatech.edu/apply/status",
  },
  uiuc: {
    name: "UIUC",
    id: "uiuc",
    appType: "Regular Decision",
    dateSubmitted: "1/2/2024",
    dateResponse: "3/3/2024",
    collegePortalWebsite: "https://myillini.illinois.edu/Apply/Application/Status",
  },
  washu: {
    name: "WashU St. Louis",
    id: "washu",
    appType: "Regular Decision",
    dateSubmitted: "1/2/2024",
    dateResponse: "3/23/2024",
    collegePortalWebsite: "https://pathway.wustl.edu/apply/status",
  },
  clemson: {
    name: "Clemson University",
    id: "clemson",
    appType: "Regular Decision",
    dateSubmitted: "1/2/2024",
    dateResponse: "3/1/2024",
    collegePortalWebsite: "https://admissions.clemson.edu/apply/status",
  },
  cmu: {
    name: "Carnegie Mellon University",
    id: "cmu",
    appType: "Regular Decision",
    dateSubmitted: "1/3/2024",
    dateResponse: "3/25/2024",
    collegePortalWebsite: "https://admission.cmu.edu/apply/status",
  }, 
  rice: { 
    name: "Rice University",
    id: "rice",
    appType: "Regular Decision",
    dateSubmitted: "1/4/2024",
    dateResponse: "3/27/2024",
    collegePortalWebsite: "https://riceadmission.rice.edu/apply/status?tab=home",
  },
  nyu: {
    name: "NYU",
    id: "nyu",
    appType: "Regular Decision",
    dateSubmitted: "1/5/2024",
    dateResponse: "3/28/2024",
    collegePortalWebsite: "https://connect.nyu.edu/portal/undergraduate",
  },
  upenn: {
    name: "UPenn",
    id: "upenn",
    appType: "Regular Decision",
    dateSubmitted: "1/5/2024",
    dateResponse: "3/30/2024",
    collegePortalWebsite: "https://key.admissions.upenn.edu/portal/applicant_status",
  },
  rpi: {
    name: "RPI",
    id: "rpi",
    appType: "Regular Decision",
    dateSubmitted: "1/9/2024",
    dateResponse: "3/2/2024",
    collegePortalWebsite: "https://apply-undergrad.rpi.edu/portal/status",
  },
};



